
format = """
[](fg:#a3aed2)\
$os\
$username\
[](fg:#a3aed2)\
[](fg:blue)\
$directory\
[](fg:blue)\
[](fg:green)\
$git_branch\
$git_state\
$git_status\
[](fg:green)\
$fill\
[](fg:yellow)\
$all(fg:black bg:yellow)\
[](fg:yellow)\
[](fg:purple)\
$cmd_duration\
[](fg:purple)\
[](fg:white)\
$time\
[](fg:white)\
$line_break\
$character"""

# pallette = 'zen'
# [palletes.zen]
# color_char1
# color_char2
# color_char3
# color_bg1
# color_bg2
# color_bg3
# color_bg4

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"

[os.symbols]
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
Mint = " "
NixOS = " "
openSUSE = " "
Pop = " "
Redhat = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "


[username]
show_always = true
style_user = "bg:#a3aed2 fg:#090c0c"
format = '[$user ]($style)'


[directory]
disabled = false
style = "bg:blue fg:white bold"
format = "[ $path ]($style)"
truncation_length = 15
truncation_symbol = "…/"
truncate_to_repo = false
# repo_root_style 
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = " "
style = "bg:green fg:black"
format = '[ $symbol $branch ]($style)'

[git_state]
style = "bg:green fg:black"
format = '[($all_status$ahead_behind )]($style)'

[git_status]
style = "bg:green fg:black"
format = '[($all_status$ahead_behind )]($style)'

[fill]
symbol = ""


[cmd_duration]
style = "fg:white bold bg:purple"
format = "[ 󱦟 $duration ]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:black bold bg:white"
format = '[  $time ]($style)'

[character]
success_symbol = "[󰅂](green)"
error_symbol = "[](red)"
vimcmd_symbol = "[󰅁](blue)"

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
style = "fg:black bg:yellow"
format = '[ $symbol$version ]($style)'

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "
style = "fg:black bg:yellow"
format = '[ $symbol$version ]($style)'

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
